// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import React from 'react';
import { shadcnComponents } from '@json-render/shadcn';
import { useStateStore } from '@json-render/react';
import type { ComponentType } from 'react';

// Import custom components from the components directory (one component per file)
import DataTable from './components/DataTable';
import Breadcrumb from './components/Breadcrumb';
import AlertDialog from './components/AlertDialog';
import MetricCard from './components/MetricCard';
import ChartComponent from './components/ChartComponent';
import EventCalendar from './components/EventCalendar';
import SegmentedRadio from './components/SegmentedRadio';

// ── Adapter: ComponentRenderProps → BaseComponentProps ──────────────────────
export function adapt(Comp: ComponentType<any>): ComponentType<any> {
  const Adapted: ComponentType<any> = ({
    element,
    children,
    emit,
    on,
    bindings,
    loading,
  }: any) => {
    let store: any;
    try {
      store = useStateStore();
    } catch {
      store = null;
    }

    const [, setTick] = React.useState(0);
    React.useEffect(() => {
      if (!store?.subscribe) return;
      const unsub = store.subscribe(() => {
        setTick((t) => t + 1);
      });
      return () => {
        if (typeof unsub === 'function') unsub();
      };
    }, [store]);

    // Intercept button press to auto-close modals and trigger toasts
    const customEmit = (eventName: string, ...args: any[]) => {
      if (eventName === 'press' && store) {
        const id = element?.props?.id ?? element?.id ?? '';
        const label = element?.props?.label ?? '';

        // Auto-switch tabs when clicking tab buttons
        if (id === 'tab-macro-trigger' || label.includes('全球宏觀') || label.includes('情緒雷達')) {
          store.set('/activeTab', 'macro-sentiment-section');
        } else if (id === 'tab-leaderboard-trigger' || label.includes('合規標的') || label.includes('天梯榜')) {
          store.set('/activeTab', 'qualified-leaderboard-section');
        } else if (id === 'tab-dca-trigger' || label.includes('定期定額') || label.includes('除息月曆')) {
          store.set('/activeTab', 'dca-calendar-section');
        }

        // Auto-switch sub-tabs inside macro-sentiment-section
        if (id === 'subtab-benchmark-trigger' || label.includes('基準指數') || label.includes('即時行情與走勢') || label.includes('近一日行情與走勢')) {
          store.set('/activeSubTab', 'macro-subtab-benchmark');
        } else if (id === 'subtab-panic-trigger' || label.includes('恐慌情緒') || label.includes('四大恐慌')) {
          store.set('/activeSubTab', 'macro-subtab-panic');
        } else if (id === 'subtab-yield-trigger' || label.includes('殖利率曲線') || label.includes('宏觀利率')) {
          store.set('/activeSubTab', 'macro-subtab-yield');
        }

        const isClosingAction =
          label === '關閉' ||
          label === '關閉抽屜' ||
          label === '取消' ||
          label === '儲存' ||
          label === '確認刪除' ||
          id.includes('cancel') ||
          id.includes('close') ||
          id.includes('submit') ||
          id.includes('confirm');
        if (isClosingAction) {
          const modals = store.get('/modals') || {};
          store.set(
            '/modals',
            Object.fromEntries(Object.keys(modals).map((k) => [k, false]))
          );
        }
      }
      if (emit) emit(eventName, ...args);
    };

    const rawProps = element?.props ?? {};
    let effectiveBindings = { ...(bindings ?? element?.bindings ?? {}) };
    let adaptedProps = { ...rawProps };

    // Resolve two-way binding for Select, Radio, Input, Tabs (value)
    if (rawProps.value && typeof rawProps.value === 'object' && '$bindState' in rawProps.value) {
      const path = rawProps.value.$bindState;
      effectiveBindings.value = path;
      if (store) {
        const valFromStore = store.get(path);
        adaptedProps.value =
          valFromStore && valFromStore !== 'all'
            ? valFromStore
            : (rawProps.defaultValue || rawProps.options?.[0] || rawProps.tabs?.[0]?.value || '');
      }
    }

    // Resolve two-way binding for Switch, Checkbox (checked)
    if (rawProps.checked && typeof rawProps.checked === 'object' && '$bindState' in rawProps.checked) {
      const path = rawProps.checked.$bindState;
      effectiveBindings.checked = path;
      if (store) {
        const checkedFromStore = store.get(path);
        adaptedProps.checked = checkedFromStore !== undefined ? checkedFromStore : true;
      }
    }

    return React.createElement(Comp, {
      props: adaptedProps,
      children,
      emit: customEmit,
      on,
      bindings: effectiveBindings,
      loading,
    });
  };
  Adapted.displayName = `Adapted(${
    (Comp as any).displayName || Comp.name || 'Component'
  })`;
  return Adapted;
}

// ── Component Registry ──────────────────────────────────────────────────────
export const componentRegistry: Record<string, ComponentType<any>> = {
  // ── 1. All @json-render/shadcn presets, adapted ─────────────────────────
  ...Object.fromEntries(
    Object.entries(shadcnComponents).map(([key, Comp]) => [
      key,
      adapt(Comp as ComponentType<any>),
    ])
  ),

  // ── 2. Custom layout shell ───────────────────────────────────────────────
  'Container:page': ({ children }: any) => (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
      {children}
    </div>
  ),

  // ── 3. Custom composites (imported from src/json-render/components/) ─────
  DataTable: DataTable, // columns/data/row-actions
  Breadcrumb: Breadcrumb, // <nav><ol> wrapper
  AlertDialog: AlertDialog, // confirm dialog overlay
  MetricCard: MetricCard, // KPI metric card
  EventCalendar: EventCalendar, // ETF Dividend & Split Calendar
  Radio: adapt(SegmentedRadio), // Inline horizontal segmented radio button group
  SegmentedRadio: adapt(SegmentedRadio),

  // ── 4. Chart wrappers (Real interactive SVG charts) ──────────────────────
  'Chart:bar': ChartComponent,
  'Chart:line': ChartComponent,
  'Chart:pie': ChartComponent,
  Chart: ChartComponent,

  // ── 5. Native HTML passthrough ───────────────────────────────────────────
  div: ({ element, children }: any) => (
    <div className={element?.props?.className}>{children}</div>
  ),
};
