// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import React from 'react';
import { shadcnComponents } from '@json-render/shadcn';
import { useStateStore } from '@json-render/react';
import type { ComponentType } from 'react';

// Import custom components from the components directory (one component per file)
import DataTable from './components/DataTable';
import Breadcrumb from './components/Breadcrumb';
import AlertDialog from './components/AlertDialog';
import MetricCard from './components/MetricCard';
import ChartPlaceholder from './components/ChartPlaceholder';

// ── Adapter: ComponentRenderProps → BaseComponentProps ──────────────────────
export function adapt(Comp: ComponentType<any>): ComponentType<any> {
  const Adapted: ComponentType<any> = ({
    element,
    children,
    emit,
    on,
    bindings,
    loading,
  }: any) => {
    let store: any;
    try {
      store = useStateStore();
    } catch {
      store = null;
    }

    // Intercept button press to auto-close modals and trigger toasts
    const customEmit = (eventName: string, ...args: any[]) => {
      if (eventName === 'press' && store) {
        const id = element?.props?.id ?? '';
        const label = element?.props?.label ?? '';
        const isClosingAction =
          label === '關閉' ||
          label === '關閉抽屜' ||
          label === '取消' ||
          label === '儲存' ||
          label === '確認刪除' ||
          id.includes('cancel') ||
          id.includes('close') ||
          id.includes('submit') ||
          id.includes('confirm');
        if (isClosingAction) {
          const modals = store.get('/modals') || {};
          store.set(
            '/modals',
            Object.fromEntries(Object.keys(modals).map((k) => [k, false]))
          );
        }
      }
      if (emit) emit(eventName, ...args);
    };

    return React.createElement(Comp, {
      props: element?.props ?? {},
      children,
      emit: customEmit,
      on,
      bindings,
      loading,
    });
  };
  Adapted.displayName = `Adapted(${
    (Comp as any).displayName || Comp.name || 'Component'
  })`;
  return Adapted;
}

// ── Component Registry ──────────────────────────────────────────────────────
export const componentRegistry: Record<string, ComponentType<any>> = {
  // ── 1. All @json-render/shadcn presets, adapted ─────────────────────────
  ...Object.fromEntries(
    Object.entries(shadcnComponents).map(([key, Comp]) => [
      key,
      adapt(Comp as ComponentType<any>),
    ])
  ),

  // ── 2. Custom layout shell ───────────────────────────────────────────────
  'Container:page': ({ children }: any) => (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
      {children}
    </div>
  ),

  // ── 3. Custom composites (imported from src/json-render/components/) ─────
  DataTable: DataTable, // columns/data/row-actions
  Breadcrumb: Breadcrumb, // <nav><ol> wrapper
  AlertDialog: AlertDialog, // confirm dialog overlay
  MetricCard: MetricCard, // KPI metric card

  // ── 4. Chart wrappers ────────────────────────────────────────────────────
  'Chart:bar': ChartPlaceholder('Bar'),
  'Chart:line': ChartPlaceholder('Line'),
  'Chart:pie': ChartPlaceholder('Pie'),
  Chart: ChartPlaceholder('Chart'),

  // ── 5. Native HTML passthrough ───────────────────────────────────────────
  div: ({ element, children }: any) => (
    <div className={element?.props?.className}>{children}</div>
  ),
};
