// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/global_asset_contract.puml (resolver: listPairwiseMatrix)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface GlobalAssetPairwiseMatrix {
  baseTicker: string;
  targetTicker: string;
  correlationCoeff: number;
  rSquared: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const listPairwiseMatrixKeys = {
  all: ['listPairwiseMatrix'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['listPairwiseMatrix', filter] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useListPairwiseMatrix(filter?: {
  assetClass?: string;
  evaluationDate?: string;
}) {
  const effectiveFilter = {
    assetClass: 'CORE',
    evaluationDate: '2026-09-01',
    ...(filter ?? {}),
  };

  return useQuery({
    queryKey: listPairwiseMatrixKeys.filtered(effectiveFilter),
    queryFn: () =>
      api
        .graphql<{ listPairwiseMatrix: GlobalAssetPairwiseMatrix[] }>(
          `query ListPairwiseMatrix($assetClass: CandidateAssetClass!, $evaluationDate: String) {
            listPairwiseMatrix(assetClass: $assetClass, evaluationDate: $evaluationDate) {
              baseTicker
              targetTicker
              correlationCoeff
              rSquared
            }
          }`,
          effectiveFilter
        )
        .then((data) => data.listPairwiseMatrix),
  });
}
