// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: listCorporateActions)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface CorporateAction {
  effectiveDate: string;
  ticker: string;
  actionType: string;
  splitToShares: number;
  splitFromShares: number;
  splitRatioNumerator?: number;
  splitRatioDenominator?: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const listCorporateActionsKeys = {
  all: ['listCorporateActions'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['listCorporateActions', filter] as const,
};

export function useListCorporateActions(
  filter?: Record<string, unknown>,
  options?: { enabled?: boolean }
) {
  return useQuery({
    queryKey: filter
      ? listCorporateActionsKeys.filtered(filter)
      : listCorporateActionsKeys.all,
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ listCorporateActions: CorporateAction[] }>(
          `query ListCorporateActions($filter: CorporateActionFilterInput) {
            listCorporateActions(filter: $filter) {
              effectiveDate
              ticker
              actionType
              splitToShares
              splitFromShares
            }
          }`,
          { filter }
        )
        .then((data) =>
          data.listCorporateActions.map((item) => ({
            ...item,
            splitRatioNumerator: item.splitToShares,
            splitRatioDenominator: item.splitFromShares,
          }))
        ),
  });
}
