// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getLatestMacroYieldSnapshot)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MacroYieldSnapshot {
  dgs10: number;
  dgs20: number;
  dgs30: number;
  dgs2: number;
  t10y2ySpread: number;
  bamlc0a0cmeyCorpYield: number;
  snapshotDate: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getLatestMacroYieldSnapshotKeys = {
  all: ['getLatestMacroYieldSnapshot'] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetLatestMacroYieldSnapshot() {
  return useQuery({
    queryKey: getLatestMacroYieldSnapshotKeys.all,
    queryFn: () =>
      api
        .graphql<{ getLatestMacroYieldSnapshot: MacroYieldSnapshot }>(
          `query GetLatestMacroYieldSnapshot {
            getLatestMacroYieldSnapshot {
              dgs10
              dgs20
              dgs30
              dgs2
              t10y2ySpread
              bamlc0a0cmeyCorpYield
              snapshotDate
            }
          }`
        )
        .then((data) => data.getLatestMacroYieldSnapshot),
  });
}
