// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getTop20DcaRanks)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface DcaPopularityRank {
  rankPosition: number;
  ticker: string;
  name: string;
  distributionFrequency?: string;
  investorCount: number;
  rankingYear: number;
  rankingMonth: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getTop20DcaRanksKeys = {
  all: ['getTop20DcaRanks'] as const,
  filtered: (year?: number, month?: number) =>
    ['getTop20DcaRanks', year, month] as const,
};

export function useGetTop20DcaRanks(
  year: number = 2026,
  month: number = 8,
  options?: { enabled?: boolean }
) {
  return useQuery({
    queryKey: getTop20DcaRanksKeys.filtered(year, month),
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ getTop20DcaRanks: DcaPopularityRank[] }>(
          `query GetTop20DcaRanks($year: Int, $month: Int) {
            getTop20DcaRanks(year: $year, month: $month) {
              rankPosition
              ticker
              name
              distributionFrequency
              investorCount
              rankingYear
              rankingMonth
            }
          }`,
          { year, month }
        )
        .then((data) => data.getTop20DcaRanks),
  });
}
