// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getQuoteTimeSeries)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MarketDailyQuote {
  ticker: string;
  tradeDate: string;
  openPrice: number;
  highPrice: number;
  lowPrice: number;
  closePrice: number;
  volume: number;
  changePct?: number;
  ma20?: number;
  ma60?: number;
  ma120?: number;
  ma240?: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getQuoteTimeSeriesKeys = {
  all: ['getQuoteTimeSeries'] as const,
  series: (ticker: string, startDate?: string, endDate?: string) =>
    ['getQuoteTimeSeries', ticker, startDate, endDate] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetQuoteTimeSeries(
  ticker?: string,
  startDate?: string,
  endDate?: string
) {
  return useQuery({
    queryKey: ticker
      ? getQuoteTimeSeriesKeys.series(ticker, startDate, endDate)
      : getQuoteTimeSeriesKeys.all,
    enabled: Boolean(ticker),
    queryFn: () =>
      api
        .graphql<{ getQuoteTimeSeries: MarketDailyQuote[] }>(
          `query GetQuoteTimeSeries($ticker: String!, $startDate: String!, $endDate: String!) {
            getQuoteTimeSeries(ticker: $ticker, startDate: $startDate, endDate: $endDate) {
              ticker
              tradeDate
              openPrice
              closePrice
              volumeShares
            }
          }`,
          { ticker, startDate: startDate ?? '', endDate: endDate ?? '' }
        )
        .then((data) =>
          (data.getQuoteTimeSeries || []).map((item) => ({
            ...item,
            volume: item.volumeShares ?? 0,
          }))
        ),
  });
}
