// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/global_asset_contract.puml (resolver: getGlobalAssetByTicker)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface GlobalAssetMetadata {
  ticker: string;
  name: string;
  assetClass: string;
  underlyingIndex?: string;
  distributionFrequency?: string;
  fundSizeTwd?: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getGlobalAssetByTickerKeys = {
  all: ['getGlobalAssetByTicker'] as const,
  detail: (ticker: string) => ['getGlobalAssetByTicker', ticker] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetGlobalAssetByTicker(ticker?: string) {
  return useQuery({
    queryKey: ticker
      ? getGlobalAssetByTickerKeys.detail(ticker)
      : getGlobalAssetByTickerKeys.all,
    enabled: Boolean(ticker),
    queryFn: () =>
      api
        .graphql<{ getGlobalAssetByTicker: GlobalAssetMetadata }>(
          `query GetGlobalAssetByTicker($ticker: String!) {
            getGlobalAssetByTicker(ticker: $ticker) {
              ticker
              name
              assetClass
              underlyingIndex
              distributionFrequency
              fundSizeTwd
            }
          }`,
          { ticker }
        )
        .then((data) => data.getGlobalAssetByTicker),
  });
}
