// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: listDividendAnnouncements)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface DividendAnnouncement {
  ticker: string;
  exDate: string;
  dividendPerShare: number;
  paymentDate: string;
  taxTag?: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const listDividendAnnouncementsKeys = {
  all: ['listDividendAnnouncements'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['listDividendAnnouncements', filter] as const,
};

export function useListDividendAnnouncements(
  filter?: Record<string, unknown>,
  options?: { enabled?: boolean }
) {
  return useQuery({
    queryKey: filter
      ? listDividendAnnouncementsKeys.filtered(filter)
      : listDividendAnnouncementsKeys.all,
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ listDividendAnnouncements: DividendAnnouncement[] }>(
          `query ListDividendAnnouncements($filter: DividendAnnouncementFilterInput) {
            listDividendAnnouncements(filter: $filter) {
              ticker
              exDate
              dividendPerShare
              paymentDate
              taxTag
            }
          }`,
          { filter }
        )
        .then((data) => data.listDividendAnnouncements),
  });
}
