// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getDipBuyOpportunity)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface DipBuyOpportunityScore {
  ticker: string;
  compositeScore: number;
  starRating: string;
  winRateEstimate: string;
  recommendation: string;
  bollingerScore?: number;
  fibonacciScore?: number;
  maSupportScore?: number;
  panicScore?: number;
  dipScore?: number;
  historical1yWinRate?: number;
  actionRecommendation?: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getDipBuyOpportunityKeys = {
  all: ['getDipBuyOpportunity'] as const,
  detail: (ticker: string) => ['getDipBuyOpportunity', ticker] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetDipBuyOpportunity(ticker?: string) {
  return useQuery({
    queryKey: ticker
      ? getDipBuyOpportunityKeys.detail(ticker)
      : getDipBuyOpportunityKeys.all,
    enabled: Boolean(ticker),
    queryFn: () =>
      api
        .graphql<{ getDipBuyOpportunity: DipBuyOpportunityScore }>(
          `query GetDipBuyOpportunity($ticker: String!) {
            getDipBuyOpportunity(ticker: $ticker) {
              ticker
              compositeScore
              starRating
              winRateEstimate
              recommendation
              bollingerScore
              fibonacciScore
              maSupportScore
              panicScore
            }
          }`,
          { ticker }
        )
        .then((data) => {
          const item = data.getDipBuyOpportunity;
          if (item) {
            item.dipScore = item.compositeScore;
            item.actionRecommendation = item.recommendation;
          }
          return item;
        }),
  });
}
