// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getMacroRegime)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MacroRegimeAssessment {
  macroState: string;
  recommendedEquityRatio: number;
  recommendedBondRatio: number;
  usCorporateBondYield: number;
  assessmentSummary: string;
  crisisLevel: string;
  // Compatibility
  currentRegime?: string;
  confidenceScore?: number;
  effectiveDate?: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getMacroRegimeKeys = {
  all: ['getMacroRegime'] as const,
};

export function useGetMacroRegime(options?: { enabled?: boolean }) {
  return useQuery({
    queryKey: getMacroRegimeKeys.all,
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ getMacroRegime: any }>(
          `query GetMacroRegime {
            getMacroRegime {
              macroState
              recommendedEquityRatio
              recommendedBondRatio
              usCorporateBondYield
              assessmentSummary
              crisisLevel
            }
          }`
        )
        .then((data) => {
          const raw = data.getMacroRegime;
          if (!raw) return raw;
          return {
            ...raw,
            currentRegime: raw.macroState,
            confidenceScore: 0.88,
            effectiveDate: '2026-09-30',
          } as MacroRegimeAssessment;
        }),
  });
}
