// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/global_asset_contract.puml (resolver: getScoreByTicker)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface GlobalAssetScoreDetail {
  ticker: string;
  evaluationDate: string;
  compositeScore: number;
  classRank: number;
  orthogonalStatus?: string;
  rSquaredWithLeader?: number;
  scoreFactors?: Record<string, number>;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getScoreByTickerKeys = {
  all: ['getScoreByTicker'] as const,
  detail: (ticker: string, evaluationDate?: string) =>
    ['getScoreByTicker', ticker, evaluationDate] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetScoreByTicker(ticker?: string, evaluationDate?: string) {
  return useQuery({
    queryKey: ticker
      ? getScoreByTickerKeys.detail(ticker, evaluationDate)
      : getScoreByTickerKeys.all,
    enabled: Boolean(ticker),
    queryFn: () =>
      api
        .graphql<{ getScoreByTicker: GlobalAssetScoreDetail }>(
          `query GetScoreByTicker($ticker: String!, $evaluationDate: String!) {
            getScoreByTicker(ticker: $ticker, evaluationDate: $evaluationDate) {
              ticker
              compositeScore
              classRank
              orthogonalStatus
              rSquaredWithLeader
            }
          }`,
          { ticker, evaluationDate: evaluationDate ?? '' }
        )
        .then((data) => data.getScoreByTicker),
  });
}
