// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getMacroRegime)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MacroRegimeAssessment {
  currentRegime: string;
  confidenceScore: number;
  assessmentSummary: string;
  effectiveDate: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getMacroRegimeKeys = {
  all: ['getMacroRegime'] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetMacroRegime() {
  return useQuery({
    queryKey: getMacroRegimeKeys.all,
    queryFn: () =>
      api
        .graphql<{ getMacroRegime: MacroRegimeAssessment }>(
          `query GetMacroRegime {
            getMacroRegime {
              currentRegime
              confidenceScore
              assessmentSummary
              effectiveDate
            }
          }`
        )
        .then((data) => data.getMacroRegime),
  });
}
