// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: listDataFeedWatermarks)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface DataFeedWatermark {
  feedName: string;
  status: string;
  latestRecordDate: string;
  recordsSyncedCount: number;
  lastSuccessfulSyncAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const listDataFeedWatermarksKeys = {
  all: ['listDataFeedWatermarks'] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useListDataFeedWatermarks() {
  return useQuery({
    queryKey: listDataFeedWatermarksKeys.all,
    queryFn: () =>
      api
        .graphql<{ listDataFeedWatermarks: DataFeedWatermark[] }>(
          `query ListDataFeedWatermarks {
            listDataFeedWatermarks {
              feedName
              status
              latestRecordDate
              recordsSyncedCount
              lastSuccessfulSyncAt
              updatedAt
            }
          }`
        )
        .then((data) => data.listDataFeedWatermarks),
  });
}
