// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/global_asset_contract.puml (resolver: getClusteredCandidates)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface ClusterAlternative {
  ticker: string;
  name: string;
  underlyingIndex?: string;
  rSquaredWithLeader: number;
  compositeScoreGap: number;
  closePrice?: number;
  changePct?: number;
  return1m?: number;
  return3m?: number;
  return6m?: number;
  return1y?: number;
  fundSizeTwd?: number;
  compositeScore?: number;
  [key: string]: unknown;
}

export interface GlobalAssetCluster {
  clusterId: number;
  leader: Record<string, unknown>;
  alternatives: ClusterAlternative[];
  isSingleton: boolean;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getClusteredCandidatesKeys = {
  all: ['getClusteredCandidates'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['getClusteredCandidates', filter] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetClusteredCandidates(filter?: {
  assetClass?: string;
  threshold?: number;
  evaluationDate?: string;
}) {
  return useQuery({
    queryKey: filter
      ? getClusteredCandidatesKeys.filtered(filter)
      : getClusteredCandidatesKeys.all,
    queryFn: () =>
      api
        .graphql<{ getClusteredCandidates: GlobalAssetCluster[] }>(
          `query GetClusteredCandidates($assetClass: CandidateAssetClass!, $threshold: Float, $evaluationDate: String) {
            getClusteredCandidates(assetClass: $assetClass, threshold: $threshold, evaluationDate: $evaluationDate) {
              clusterId
              isSingleton
              leader {
                ticker
                name
                underlyingIndex
                closePrice
                changePct
                return1m
                return3m
                return6m
                return1y
                fundSizeTwd
                compositeScore
              }
              alternatives {
                ticker
                name
                underlyingIndex
                rSquaredWithLeader
                compositeScoreGap
                closePrice
                changePct
                return1m
                return3m
                return6m
                return1y
                fundSizeTwd
                compositeScore
              }
            }
          }`,
          filter
        )
        .then((data) => data.getClusteredCandidates),
  });
}
