// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: listMacroYieldSnapshots)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MacroYieldSnapshotItem {
  id?: string;
  recordDate: string;
  usCorporateBondEffectiveYield: number;
  us10YearTreasuryYield: number;
  us20YearTreasuryYield: number;
  yieldSpread10yMinus2y: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const listMacroYieldSnapshotsKeys = {
  all: ['listMacroYieldSnapshots'] as const,
  filtered: (filter?: Record<string, unknown>) =>
    ['listMacroYieldSnapshots', filter] as const,
};

export function useListMacroYieldSnapshots(
  filter?: {
    startDate?: string;
    endDate?: string;
  },
  options?: { enabled?: boolean }
) {
  const queryFilter = filter ?? {
    startDate: '2025-10-01',
    endDate: '2026-09-30',
  };

  return useQuery({
    queryKey: listMacroYieldSnapshotsKeys.filtered(queryFilter),
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ listMacroYieldSnapshots: MacroYieldSnapshotItem[] }>(
          `query ListMacroYieldSnapshots($filter: MacroYieldFilterInput) {
            listMacroYieldSnapshots(filter: $filter) {
              id
              recordDate
              usCorporateBondEffectiveYield
              us10YearTreasuryYield
              us20YearTreasuryYield
              yieldSpread10yMinus2y
            }
          }`,
          { filter: queryFilter }
        )
        .then((data) => data.listMacroYieldSnapshots || []),
  });
}
