// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/global_asset_contract.puml (resolver: getClusteredCandidates)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface ClusterAlternative {
  ticker: string;
  name: string;
  classRank?: number;
  underlyingIndex?: string;
  distributionFrequency?: string;
  rSquaredWithLeader: number;
  compositeScoreGap: number;
  closePrice?: number;
  changePct?: number;
  return1m?: number;
  return3m?: number;
  return6m?: number;
  return1y?: number;
  fundSizeTwd?: number;
  compositeScore?: number;
  [key: string]: unknown;
}

export interface GlobalAssetCluster {
  clusterId: number;
  leader: Record<string, unknown>;
  alternatives: ClusterAlternative[];
  isSingleton: boolean;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getClusteredCandidatesKeys = {
  all: ['getClusteredCandidates'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['getClusteredCandidates', filter] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetClusteredCandidates(
  filter?: {
    assetClass?: string;
    threshold?: number;
    evaluationDate?: string;
  },
  options?: { enabled?: boolean }
) {
  const now = new Date();
  const defaultEvalDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-01`;

  const effectiveFilter = {
    assetClass: 'CORE',
    threshold: 0.8,
    evaluationDate: defaultEvalDate,
    ...(filter ?? {}),
  };

  return useQuery({
    queryKey: getClusteredCandidatesKeys.filtered(effectiveFilter),
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ getClusteredCandidates: GlobalAssetCluster[] }>(
          `query GetClusteredCandidates($assetClass: CandidateAssetClass!, $threshold: Float, $evaluationDate: String) {
            getClusteredCandidates(assetClass: $assetClass, threshold: $threshold, evaluationDate: $evaluationDate) {
              clusterId
              isSingleton
              leader {
                ticker
                name
                classRank
                underlyingIndex
                distributionFrequency
                closePrice
                changePct
                return1m
                return3m
                return6m
                return1y
                fundSizeTwd
                compositeScore
              }
              alternatives {
                rSquared
                score {
                  ticker
                  name
                  classRank
                  underlyingIndex
                  distributionFrequency
                  closePrice
                  changePct
                  return1m
                  return3m
                  return6m
                  return1y
                  fundSizeTwd
                  compositeScore
                }
              }
            }
          }`,
          effectiveFilter
        )
        .then((data) => {
          const list = data?.getClusteredCandidates || [];
          return list.map((c: any) => ({
            ...c,
            alternatives: (c.alternatives || []).map((alt: any) => {
              if (alt.score) {
                return {
                  ...alt.score,
                  ...alt,
                  rSquaredWithLeader: alt.rSquared ?? alt.rSquaredWithLeader,
                };
              }
              return alt;
            }),
          }));
        }),
  });
}
