// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/global_asset_contract.puml (resolver: getOrthogonalCandidates)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface GlobalAssetScore {
  ticker: string;
  name?: string;
  classRank?: number;
  distributionFrequency?: string;
  orthogonalStatus?: string;
  collisionDetail?: string;
  closePrice?: number;
  changePct?: number;
  return1m?: number;
  return3m?: number;
  return6m?: number;
  return1y?: number;
  fundSizeTwd?: number;
  compositeScore?: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getOrthogonalCandidatesKeys = {
  all: ['getOrthogonalCandidates'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['getOrthogonalCandidates', filter] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetOrthogonalCandidates(
  filter?: {
    assetClass?: string;
    seedTicker?: string;
    evaluationDate?: string;
  },
  options?: { enabled?: boolean }
) {
  const now = new Date();
  const defaultEvalDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-01`;

  const effectiveFilter = {
    assetClass: 'CORE',
    seedTicker: '0050',
    evaluationDate: defaultEvalDate,
    ...(filter ?? {}),
  };

  return useQuery({
    queryKey: getOrthogonalCandidatesKeys.filtered(effectiveFilter),
    enabled: options?.enabled,
    queryFn: () =>
      api
        .graphql<{ getOrthogonalCandidates: GlobalAssetScore[] }>(
          `query GetOrthogonalCandidates($assetClass: CandidateAssetClass!, $seedTicker: String, $evaluationDate: String) {
            getOrthogonalCandidates(assetClass: $assetClass, seedTicker: $seedTicker, evaluationDate: $evaluationDate) {
              ticker
              name
              classRank
              distributionFrequency
              compositeScore
              rSquared
              orthogonalStatus
              collisionDetail
              closePrice
              changePct
              return1m
              return3m
              return6m
              return1y
              fundSizeTwd
            }
          }`,
          effectiveFilter
        )
        .then((data) => data.getOrthogonalCandidates),
  });
}
