// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: listMarketDailyQuotes)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MarketDailyQuoteItem {
  ticker: string;
  tradeDate: string;
  openPrice?: number;
  highPrice?: number;
  lowPrice?: number;
  closePrice: number;
  volumeShares?: number;
  changePct?: number;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const listMarketDailyQuotesKeys = {
  all: ['listMarketDailyQuotes'] as const,
  filtered: (filter: Record<string, unknown>) =>
    ['listMarketDailyQuotes', filter] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useListMarketDailyQuotes(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter
      ? listMarketDailyQuotesKeys.filtered(filter)
      : listMarketDailyQuotesKeys.all,
    queryFn: () =>
      api
        .graphql<{ listMarketDailyQuotes: MarketDailyQuoteItem[] }>(
          `query ListMarketDailyQuotes($filter: MarketDailyQuoteFilterInput) {
            listMarketDailyQuotes(filter: $filter) {
              ticker
              tradeDate
              openPrice
              highPrice
              lowPrice
              closePrice
              volumeShares
            }
          }`,
          { filter }
        )
        .then((data) =>
          (data.listMarketDailyQuotes || []).map((q) => ({
            ...q,
            changePct:
              q.changePct !== undefined
                ? q.changePct
                : q.openPrice && q.closePrice
                ? Number(
                    (((q.closePrice - q.openPrice) / q.openPrice) * 100).toFixed(2)
                  )
                : 0,
          }))
        ),
  });
}
