// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/market_intelligence_contract.puml (resolver: getLatestMacroYieldSnapshot)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

// ── Response Type ──────────────────────────────────────────────────────────
export interface MacroYieldSnapshot {
  recordDate: string;
  usCorporateBondEffectiveYield: number;
  us10YearTreasuryYield: number;
  us20YearTreasuryYield: number;
  yieldSpread10yMinus2y: number;
  // Compatibility getters
  dgs10?: number;
  dgs20?: number;
  t10y2ySpread?: number;
  bamlc0a0cmeyCorpYield?: number;
  snapshotDate?: string;
  [key: string]: unknown;
}

// ── Query Key Factory ──────────────────────────────────────────────────────
export const getLatestMacroYieldSnapshotKeys = {
  all: ['getLatestMacroYieldSnapshot'] as const,
};

// ── Hook ───────────────────────────────────────────────────────────────────
export function useGetLatestMacroYieldSnapshot() {
  return useQuery({
    queryKey: getLatestMacroYieldSnapshotKeys.all,
    queryFn: () =>
      api
        .graphql<{ getLatestMacroYieldSnapshot: any }>(
          `query GetLatestMacroYieldSnapshot {
            getLatestMacroYieldSnapshot {
              recordDate
              usCorporateBondEffectiveYield
              us10YearTreasuryYield
              us20YearTreasuryYield
              yieldSpread10yMinus2y
            }
          }`
        )
        .then((data) => {
          const raw = data.getLatestMacroYieldSnapshot;
          if (!raw) return raw;
          return {
            ...raw,
            snapshotDate: raw.recordDate,
            dgs10: raw.us10YearTreasuryYield,
            dgs20: raw.us20YearTreasuryYield,
            t10y2ySpread: raw.yieldSpread10yMinus2y,
            bamlc0a0cmeyCorpYield: raw.usCorporateBondEffectiveYield,
          } as MacroYieldSnapshot;
        }),
  });
}
